### ISSUE TITLE
Test image resolution.

### ISSUE THREAD

**Issue by Ballzy0706** [Wang-xjtu/G2-MonoDepth#3]
Thank you for your great work. 
I had a question - is the resolution of the test images fixed? Also, if I have a custom dataset, would it be possible to use your model to estimate depth from those images?

**Comment by Wang-xjtu** [comment]
Hi. 
1. The resolution of the test images can be flexible (since there are 5 downsampling layers, it must be a multiple of 64). Notably, we recommend resizing the test images to 320 in height for better performance.
2. The model can be used for custom datasets. The input data of the network should be normalized to [0, 1], you can refer to the data pipeline in [src/data_tools.py](https://github.com/Wang-xjtu/G2-MonoDepth/blob/main/src/data_tools.py)

**Comment by Ballzy0706** [comment]
Thank you for your reply! I noticed that in the test data you provided, the depth maps are all 16-bit, so they were divided by 65,536 during data preprocessing. For a custom dataset, would the normalization process change to divide by the maximum depth value instead?

**Comment by Ballzy0706** [comment]
Thank you for your reply!
I noticed that in the test data you provided, the depth maps are all 16-bit, so they were divided by 65,536 during data preprocessing. 
For a custom dataset, would the normalization process change to divide by the maximum depth value instead?

**Comment by Wang-xjtu** [comment]
Sure, you can use the maximum depth value of datasets, just keep the input data in the range [0, 1].

**Comment by Ballzy0706** [comment]
I would also like to ask for advice on changing the size of the depth maps. 
If I simply use methods like image resizing, for example `cv2.resize(rgb, (320, ...), interpolation=cv2.INTER_AREA).astype(np.uint8)`, the resulting depth map will have incorrect values at the junctions between foreground and background objects. 
Do you have any suggestions or recommended ways to resize depth maps properly? Any advice would be greatly appreciated.

**Comment by Wang-xjtu** [comment]
You should use the "Nearest" mode to resize depth maps. Incorrect values may be caused by incorrect interpolation between pixels in valid areas and invalid areas (i.e. holes).

**Comment by Ballzy0706** [comment]
I've tried resizing the image using the "INTER_AREA" mode as well as the "Nearest" mode for the depth map, but the final result still looks strange. The most noticeable issue is that after depth completion, the resulting object appears to be a circle larger than the outline of the object in the RGB image. 
May I ask if this is caused by the different datasets differing?

**Comment by Ballzy0706** [comment]
Alternatively, if it would be easier for you, I can email you some pictures of my results so you can better understand the issue I'm describing.

**Comment by Wang-xjtu** [comment]
I'm not sure the reason of this problem. I don't encounter this problem even when testing on different zero-shot datasets listed in the paper.

**Comment by Ballzy0706** [comment]
Thank you for your patience!
